lab5
Dima1234566/MobDev pull request #7
Opened 2018-10-19 17:34 UTC by Dima1234566

-

2018-10-31 14:27 UTC, iRafal commented on lab5/app/build.gradle
> +    implementation 'com.android.support:appcompat-v7:28.0.0'
fix warning

2018-10-31 14:28 UTC, iRafal commented on lab5/app/src/main/java/e/dimas/lab5/Api.java
> +    String Base_URL = "http://www.amiiboapi.com/api/amiibo/";
static final

2018-10-31 14:28 UTC, iRafal commented on lab5/app/src/main/java/e/dimas/lab5/Api.java
> +public interface Api {
too much empty lines.

2018-11-22 08:19 UTC, MarkoKuspis requested changes

2018-11-22 08:19 UTC, MarkoKuspis commented on lab5/.gitignore
> +/.idea/workspace.xml
/.idea/*

2018-11-22 08:19 UTC, MarkoKuspis commented on lab5/app/build.gradle
> +    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
You don't use any of two libraries above

2018-11-22 08:19 UTC, MarkoKuspis commented on lab5/app/build.gradle
> +    testImplementation 'junit:junit:4.12'
You don't use it as well

2018-11-22 08:19 UTC, MarkoKuspis commented on lab5/app/src/androidTest/java/e/dimas/lab5/ExampleInstrumentedTest.java
> +}
Drop this file

2018-11-22 08:19 UTC, MarkoKuspis commented on lab5/app/src/main/java/e/dimas/lab5/MainActivity.java
> +        @Override
Indentation for this file is incorrect

2018-11-22 08:19 UTC, MarkoKuspis commented on lab5/app/src/main/java/e/dimas/lab5/MainActivity.java
> +        ListView listView;
private

2018-11-22 08:19 UTC, MarkoKuspis commented on lab5/app/src/main/java/e/dimas/lab5/Photo.java
> +    private String name;
```suggestion
    private final String name;
```

2018-11-22 09:10 UTC, MarkoKuspis approved these changes

2018-11-26 09:42 UTC, merged